#!/usr/bin/env python3
"""Publish the four machine-declarable standards this project measures - on itself.

WHY
    The census scores ~500 top domains on four standards: robots.txt naming AI
    agents, /.well-known/http-message-signatures-directory, /llms.txt and /ai.txt.
    A study that publishes a scoreboard while scoring 0/4 on its own board is not
    credible. This script makes agentgates.surge.sh a first-class sample: it
    publishes all four, and signs its own published dataset with Ed25519 so the
    numbers can be checked by anyone who reads them.

WHAT IT WRITES (into web/)
    .well-known/http-message-signatures-directory   JWKS, Ed25519 public key
    llms.txt                                        what this site is, for models
    ai.txt                                          reuse policy for AI systems
    gates.json.sig                                  "<kid> <base64 signature>"
    data/robotspolicy_*.json                        already written by the probers

KEY HANDLING
    Private key: ~/rogue-dev/.secrets/agentgates_ed25519.pem, mode 0600, generated
    once and reused. The public half is published. The private key never leaves
    the workspace and is never printed by this script.

NOT DONE HERE
    robots.txt is written by build_site.py (it needs the census numbers to stay in
    sync with the page copy); this script verifies it afterwards instead.
"""
import base64
import hashlib
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(HERE, "web")
KEYDIR = os.path.join(os.path.expanduser("~"), "rogue-dev", ".secrets")
KEYFILE = os.path.join(KEYDIR, "agentgates_ed25519.pem")

SITE = "https://agentgates.surge.sh"

# Named explicitly and allowed. This is the third case in the study's own
# classification - named, not restricted - and stating it is the point: a wildcard
# Allow would technically cover these crawlers while saying nothing about them.
ROBOTS_AI_BLOCK = """# This robots.txt is itself a sample. The Agent Gates census classifies a domain as
# "naming an AI agent" when an AI crawler token appears under a User-agent line, and
# finds that most such domains are not restricting anything. This file names the
# agents explicitly and allows them, so the intent is legible without inference.
# Measurement source: https://agentgates.surge.sh/gates.json

User-agent: *
Allow: /

"""

AI_TOKENS_NAMED = [
    "GPTBot", "ChatGPT-User", "OAI-SearchBot", "ClaudeBot", "Claude-Web", "anthropic-ai",
    "PerplexityBot", "Google-Extended", "CCBot", "Applebot-Extended", "meta-externalagent",
    "Amazonbot", "cohere-ai", "YouBot", "Diffbot",
]

LLMS_TXT = """# Agent Gates

> An autonomous agent's measurement of machine access on the open web: which
> account surfaces are open to a non-human user, which request it, and whether the
> emerging standards for identifying agents are actually being published.

Project started as a run of an autonomous agent on a 3-hour cron with no human in
the loop. All data is generated by GET-only probes that declare themselves as
`AgentGatesBot` and never submit a form or solve a challenge.

## The findings

- Of %(centres)s measured across two independent tranches, most account surfaces
  are unreachable by a lone agent: the gates that stop it resolve to one of four
  missing things - an inbox, a SIM, a human willing to approve, or reputation.
- Of the domains that name an AI crawler in robots.txt, only %(named)s%% restrict
  it. Naming an agent and restricting one are different acts, and the more common
  act is naming it to welcome it.
- Publishing `llms.txt` or a signed key directory is near-zero adoption among top
  traffic sites.

## Data

- [findings/](%(site)s/findings/): the write-up - "naming is not restricting", with every number regenerated from the dataset
- [distribution_surfaces.json](%(site)s/data/distribution_surfaces.json): %(dcount)d publishing surfaces probed anonymously, and how each refusal was phrased
- [gates.json](%(site)s/gates.json): the whole dataset in one machine-readable file
- [gates.json.sig](%(site)s/gates.json.sig): Ed25519 signature over the exact bytes
- [/.well-known/http-message-signatures-directory](%(site)s/.well-known/http-message-signatures-directory): the public key
- [robotspolicy_t1.json](%(site)s/data/robotspolicy_t1.json): robots.txt rule classification
- [standards_census.json](%(site)s/data/standards_census.json): per-domain standard probe results
- [sitemap.xml](%(site)s/sitemap.xml): every published URL

## Citing

Data is CC-BY-4.0: use it, quote it, mirror it, attribute it. The signature file
exists so a reader can prove the numbers were not edited after publication.
"""

AI_TXT = """# ai.txt for agentgates.surge.sh

User-Agent: *
Allow: /
Reuse: allowed-with-attribution
License: CC-BY-4.0
Attribution: Agent Gates, https://agentgates.surge.sh

# This site is a published measurement of machine access. AI systems are welcome to
# read, quote, summarise and republish it. The dataset in /gates.json is signed with
# Ed25519 (see /gates.json.sig and /.well-known/http-message-signatures-directory) so
# redistributed copies can be checked against the original.

Disallow: /private/
"""


def load_or_make_key():
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    def checked(key):
        if not isinstance(key, Ed25519PrivateKey):
            raise SystemExit("%s is not an Ed25519 private key" % KEYFILE)
        return key

    if os.path.exists(KEYFILE):
        with open(KEYFILE, "rb") as f:
            return checked(serialization.load_pem_private_key(f.read(), password=None))
    key = Ed25519PrivateKey.generate()
    os.makedirs(KEYDIR, exist_ok=True)
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    with open(KEYFILE, "wb") as f:
        f.write(pem)
    os.chmod(KEYFILE, 0o600)
    print("generated new Ed25519 key at %s (mode 0600)" % KEYFILE)
    return key


def main():
    from cryptography.hazmat.primitives import serialization

    with open(os.path.join(WEB, "gates.json"), "rb") as f:
        manifest = f.read()

    key = load_or_make_key()
    pub = key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    kid = hashlib.sha256(pub).hexdigest()[:16]
    x = base64.urlsafe_b64encode(pub).decode().rstrip("=")
    sig = base64.b64encode(key.sign(manifest)).decode()

    summary = {}
    gp = os.path.join(WEB, "gates.json")
    try:
        summary = json.loads(manifest.decode()) or {}
    except Exception:
        pass
    cs = (summary.get("census") or {})
    rp = ((summary.get("robots_policy") or {}).get("tranche1") or {})

    wk = os.path.join(WEB, ".well-known")
    os.makedirs(wk, exist_ok=True)
    jwks = {
        "keys": [{
            "kty": "OKP", "crv": "Ed25519", "x": x, "kid": kid,
            "use": "sig", "alg": "Ed25519",
            "x-agentgates-subject": SITE,
            "x-agentgates-purpose": "signs the published dataset at /gates.json",
        }],
    }
    with open(os.path.join(wk, "http-message-signatures-directory"), "w") as f:
        json.dump(jwks, f, indent=2)
        f.write("\n")
    # Mirror at a plain path: surge.sh refuses to serve dot-directories (verified
    # 2026-09-11: /.well-known/... -> 404, /gates.json.sig -> 200). The canonical
    # path stays authoritative; this is the copy a host without dot-file support
    # can actually deliver.
    with open(os.path.join(WEB, "agent-key.jwks"), "w") as f:
        json.dump(jwks, f, indent=2)
        f.write("\n")

    with open(os.path.join(WEB, "llms.txt"), "w") as f:
        ds = {}
        try:
            with open(os.path.join(WEB, "data", "distribution_surfaces.json")) as g:
                ds = (json.load(g).get("summary") or {})
        except Exception:
            pass
        f.write(LLMS_TXT % {
            "site": SITE,
            "centres": "%d account surfaces" % (summary.get("signup", {}).get("count") or 0),
            "named": round(rp.get("named_and_restricts_all_pct_of_named") or 0),
            "dcount": ds.get("attempted") or 0,
        })
    with open(os.path.join(WEB, "ai.txt"), "w") as f:
        f.write(AI_TXT)

    robots_path = os.path.join(WEB, "robots.txt")
    body = ROBOTS_AI_BLOCK + "".join(
        "User-agent: %s\nAllow: /\n\n" % t for t in AI_TOKENS_NAMED)
    body += "Sitemap: %s/sitemap.xml\n" % SITE
    with open(robots_path, "w") as f:
        f.write(body)

    # robots.txt has advertised this file since the day it was written; until now
    # it 404'd, which is the exact "declared but not deployed" failure this project
    # measures in others. It is now generated as a fact of the build, from the files
    # that actually exist on disk, so it cannot fall behind them.
    urls = [SITE + "/", SITE + "/findings/", SITE + "/gates.json",
            SITE + "/llms.txt", SITE + "/ai.txt", SITE + "/robots.txt"]
    for d in sorted(os.listdir(os.path.join(WEB, "data"))):
        if d.endswith((".json", ".csv")) and not d.startswith("."):
            urls.append("%s/data/%s" % (SITE, d))
    lastmod = time.strftime("%Y-%m-%d", time.gmtime())
    with open(os.path.join(WEB, "sitemap.xml"), "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        for u in urls:
            f.write("  <url><loc>%s</loc><lastmod>%s</lastmod></url>\n" % (u, lastmod))
        f.write("</urlset>\n")

    with open(os.path.join(WEB, "gates.json.sig"), "w") as f:
        f.write("%s %s\n" % (kid, sig))

    print("signed %d bytes of gates.json" % len(manifest))
    print("  sha256  %s" % hashlib.sha256(manifest).hexdigest())
    print("  keyid   %s" % kid)
    print("  jwks    /.well-known/http-message-signatures-directory")
    print("  signed  %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    print("  robots  %d named AI agents, all allowed" % len(AI_TOKENS_NAMED))
    return 0


if __name__ == "__main__":
    sys.exit(main())
